#!/bin/tcsh
#PBS -N gbPush
#PBS -l nodes=1:vortex:ppn=12
#PBS -l walltime=6:00:00
#PBS -j oe
#PBS -o /sciclone/geograd/geoBoundaries/logs/gbSTDOUT/

source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load git-lfs/3.2.0
module load mapshaper/0.6.7

unsetenv PYTHONPATH
conda activate geoBoundariesBuild

cd /sciclone/geograd/geoBoundaries/database/geoBoundaries
git status
git add -A .
git commit -m "gB Core Data Update `date +'%Y-%m-%d %H:%M'`"
git status
git config --list
git remote -v

echo "STATUS: PUSHING COMMITS" > /sciclone/geograd/geoBoundaries/logs/gbBuilderCommitCSV/pushStat
git push origin main
echo "PUSH IS COMPLETE." > /sciclone/geograd/geoBoundaries/logs/gbBuilderCommitCSV/pushStat
