#!/bin/tcsh
#PBS -N gbBuilder
#PBS -l nodes=20:bora:ppn=20
#PBS -l walltime=6:00:00
#PBS -j oe
#PBS -o /sciclone/geograd/geoBoundaries/logs/gbSTDOUT/

source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load python/usermodules
module load mapshaper/0.6.7
#module load mvapich2-ib
module load intel/mpi


unsetenv PYTHONPATH

conda activate geoBoundariesBuild
cd /sciclone/geograd/geoBoundaries/scripts/geoBoundaryBot/geoBoundaryBuilder
mvp2run python build.py >& buildLog
