#!/bin/tcsh
#PBS -N gbBuildCommit
#PBS -l nodes=1:vortex:ppn=12
#PBS -l walltime=24:00:00
#PBS -j oe

source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load git-lfs/3.2.0
unsetenv PYTHONPATH
conda activate geoBoundariesBuild

cd /sciclone/geograd/geoBoundaries/scripts/geoBoundaryBot/geoBoundaryBuilder
python gitCommitMetaBuild.py