apiVersion: v1
kind: Pod
metadata:
  name: nfs-mount-tester
  #namespace: geoboundaries
spec:
  restartPolicy: OnFailure
  securityContext:
    runAsUser: 71032
    runAsGroup: 9915
  containers:
    - name: nfs-mount-tester
      image: "alpine:latest"
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - name: nfs-volume
          mountPath: "/mnt/nfs"
  volumes:
    - name: nfs-volume
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd/
