#!/bin/tcsh
#PBS -N gbBuilder
#PBS -l nodes=1:bora:ppn=20
#PBS -l walltime=00:30:00
#PBS -j oe

module load git-lfs/3.2.0

cd /sciclone/geograd/geoBoundaries/database/geoBoundaries
git pull >& /sciclone/geograd/geoBoundaries/logs/gbBuilderCron/gitPullLog.log
git lfs pull >& /sciclone/geograd/geoBoundaries/logs/gbBuilderCron/gitLFSLog.log