#!/bin/tcsh
#PBS -N gbBuilder
#PBS -l nodes=1:bora:ppn=20
#PBS -l walltime=00:30:00
#PBS -j oe

module load git-lfs/3.2.0

cd /sciclone/home20/dsmillerrunfol/geoBoundaries/
git pull &> /sciclone/home20/dsmillerrunfol/geoBoundaryBot/geoBoundaryBuilder/logs/gitPullLog.log
git lfs pull &> /sciclone/home20/dsmillerrunfol/geoBoundaryBot/geoBoundaryBuilder/logs/gitLFSLog.log