#!/bin/tcsh
#PBS -N gbPush
#PBS -l nodes=1:bora:ppn=20
#PBS -l walltime=6:00:00
#PBS -j oe
#PBS -o /sciclone/geograd/geoBoundaries/logs/gbSTDOUT/

source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load git-lfs/3.2.0
module load git/2.9.5
module load mapshaper/0.6.7

unsetenv PYTHONPATH
conda activate geoBoundariesBuild

cd /sciclone/geograd/geoBoundaries/database/geoBoundaries
git add -A .
git commit -m "Automated Nightly Build"

cd /sciclone/geograd/geoBoundaries/scripts/geoBoundaryBot/geoBoundaryBuilder

echo "STATUS: PUSHING COMMITS" > /sciclone/geograd/geoBoundaries/logs/gbBuilderCommitCSV/pushStat
python gitPush.py >& /sciclone/geograd/geoBoundaries/logs/gbBuilderCommitCSV/pushLog.log
echo "PUSH IS COMPLETE." > /sciclone/geograd/geoBoundaries/logs/gbBuilderCommitCSV/pushStat
cat /sciclone/geograd/geoBoundaries/logs/gbBuilderCommitCSV/pushLog.log