apiVersion: v1
kind: Pod
metadata:
  name: prefect-server
  namespace: geoboundaries
spec:
  restartPolicy: Always
  securityContext:
    runAsUser: 71032
    runAsGroup: 9915
  containers:
    - name: prefect-server
      image: prefecthq/prefect:2.10.5
      command: ["prefect", "server", "start"]
      args:
        - "--host"
        - "0.0.0.0" # Bind to all network interfaces
      ports:
        - containerPort: 4200 # Prefect GUI default port
      env:
        - name: PREFECT_SERVER_DATABASE_CONNECTION_URL
          value: "sqlite:////sciclone/geograd/geoBoundaries/prefect/prefect.db"
        - name: PREFECT_HOME
          value: "/sciclone/geograd/geoBoundaries/prefect"
      volumeMounts:
        - name: prefect-persistence
          mountPath: "/sciclone/geograd/geoBoundaries/prefect"
  volumes:
    - name: prefect-persistence
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd/geoBoundaries/prefect
---
apiVersion: v1
kind: Service
metadata:
  name: prefect-service
  namespace: geoboundaries
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 30000 # Exposed port for external access
  selector:
    app: prefect-server
