#!/bin/tcsh
#PBS -N gbBuilder
#PBS -l nodes=2:vortex:ppn=12
#PBS -l walltime=24:00:00
#PBS -j oe

source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load python/usermodules
module load mapshaper/0.6.7
module load mvapich2-ib


unsetenv PYTHONPATH

conda activate geoBoundariesBuild

cd /sciclone/home20/dsmillerrunfol/geoBoundaryBot/geoBoundaryBuilder
mvp2run python build.py >& buildLog