#!/bin/tcsh
#PBS -N gbBuilder
#PBS -l nodes=1:vortex:ppn=12
#PBS -l walltime=24:00:00
#PBS -j oe

source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load python/usermodules

unsetenv PYTHONPATH

conda activate geoBoundaries

cd /sciclone/home20/dsmillerrunfol/geoBoundaryBot/geoBoundaryBuilder
python build.py >& buildLog