apiVersion: v1
kind: Pod
metadata:
  name: prefect-server
  namespace: geoboundaries
  labels:
    app: prefect-server # Ensures the service can select this pod
spec:
  restartPolicy: Always
  securityContext:
    runAsUser: 71032
    runAsGroup: 9915
  containers:
    - name: prefect-server
      image: prefecthq/prefect:2.20-python3.10-kubernetes
      command: ["prefect", "server", "start"]
      args:
        - "--host"
        - "0.0.0.0" # Bind to all network interfaces
      ports:
        - containerPort: 4200 # Prefect GUI default port
      env:
        - name: PREFECT_SERVER_DATABASE_CONNECTION_URL
          value: "sqlite:////sciclone/geograd/geoBoundaries/prefect/prefect.db"
        - name: PREFECT_HOME
          value: "/sciclone/geograd/geoBoundaries/prefect"
        - name: PREFECT_SERVER_UI_STATIC_PATH
          value: "/sciclone/geograd/geoBoundaries/prefect/ui_build" # Explicit path for UI static files
      volumeMounts:
        - name: prefect-persistence
          mountPath: "/sciclone/geograd/geoBoundaries/prefect"
        - name: ui-static
          mountPath: "/usr/local/lib/python3.10/site-packages/prefect/server/ui_build"
      lifecycle:
        postStart:
          exec:
            command: ["sh", "-c", "mkdir -p /sciclone/geograd/geoBoundaries/prefect/ui_build && chmod -R 775 /sciclone/geograd/geoBoundaries/prefect/ui_build"]
  volumes:
    - name: prefect-persistence
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd/geoBoundaries/prefect
    - name: ui-static
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd/geoBoundaries/prefect/ui_build
---
apiVersion: v1
kind: Service
metadata:
  name: prefect-service-nodeport
  namespace: geoboundaries
spec:
  selector:
    app: prefect-server # Matches the app label on the pod
  type: NodePort # External access via a specific port
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 30000 # External port for access
