apiVersion: v1
kind: Pod
metadata:
  name: geoboundaries-postgres
  namespace: geoboundaries
  labels:
    app: geoboundaries-postgres
spec:
  containers:
  - name: postgres
    image: postgis/postgis:14-3.3  # Use the PostGIS-enabled image
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: "geoboundaries"
    - name: POSTGRES_PASSWORD
      value: ""
    - name: POSTGRES_DB
      value: "geoboundaries"
    - name: POSTGRES_HOST_AUTH_METHOD
      value: "trust"  # Allow connections without a password
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
    resources:
      requests:
        memory: "32Gi"
        cpu: "8"
      limits:
        memory: "32Gi"
        cpu: "8"
  volumes:
  - name: postgres-data
    nfs:
      server: 128.239.59.144
      path: /sciclone/geograd/geoBoundaries/postgres
---
apiVersion: v1
kind: Service
metadata:
  name: geoboundaries-postgres-service
  namespace: geoboundaries
spec:
  selector:
    app: geoboundaries-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
