apiVersion: v1
kind: Pod
metadata:
  name: gbdev
  namespace: geoboundaries
spec:
  securityContext:
    runAsUser: 71032
    runAsGroup: 9915
  containers:
    - name: gb-dev-container
      image: ghcr.io/wmgeolab/gb-base:latest # Replace with your custom image name
      imagePullPolicy: Always # Always pull the latest image
      command: ["/bin/sh", "-c"] # Keep the container running
      args:
        - |
          export KUBECONFIG=/sciclone/geograd/geoBoundaries/.kube/config; 
          echo "Pod is ready for interactive jobs. Use kubectl exec to interact."; 
          while true; do sleep 3600; done
      env:
        - name: KUBECONFIG
          value: /sciclone/geograd/geoBoundaries/.kube/config
      resources:
        requests:
          memory: "16Gi"
          cpu: "2"
        limits:
          memory: "16Gi"
          cpu: "2"
      volumeMounts:
        - name: nfs-mount
          mountPath: /sciclone/geograd/geoBoundaries
  volumes:
    - name: nfs-mount
      nfs:
        server: 128.239.59.144 
        path: /sciclone/geograd/geoBoundaries
