apiVersion: v1
kind: Pod
metadata:
  name: notebook
  namespace: geoboundaries
spec:
  securityContext:
    runAsUser: 71032
    runAsGroup: 9915
  containers:
    - name: notebook-container
      image: jupyter/base-notebook:latest # Jupyter Notebook base image
      imagePullPolicy: Always # Always pull the latest image
      command: ["/bin/bash", "-c"]
      args:
        - |
          start-notebook.sh --NotebookApp.ip=0.0.0.0 --NotebookApp.port=8888 --NotebookApp.token='';
      env:
        - name: KUBECONFIG
          value: /sciclone/geograd/geoBoundaries/.kube/config
      ports:
        - containerPort: 8888 # Jupyter Notebook port
      resources:
        requests:
          memory: "16Gi"
          cpu: "2"
        limits:
          memory: "16Gi"
          cpu: "2"
      volumeMounts:
        - name: nfs-mount
          mountPath: /sciclone/geograd/geoBoundaries
        - name: notebook-home
          mountPath: /home/jovyan
  volumes:
    - name: nfs-mount
      nfs:
        server: 128.239.59.144 
        path: /sciclone/geograd/geoBoundaries
    - name: notebook-home
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd/geoBoundaries/notebook
---
apiVersion: v1
kind: Service
metadata:
  name: notebook-service
  namespace: geoboundaries
spec:
  selector:
    app: notebook
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30036 # Adjust the NodePort as needed
  type: NodePort
