apiVersion: v1
kind: Pod
metadata:
  name: geoboundaries-monitor
  namespace: geoboundaries
  labels:
    app: geoboundaries-monitor
spec:
  securityContext:
    runAsUser: 71032
    runAsGroup: 9915
  containers:
  - name: monitor
    image: ghcr.io/wmgeolab/gb-monitor:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 5000
    resources:
      requests:
        ephemeral-storage: "5Gi"
      limits:
        ephemeral-storage: "5Gi"
    env:
    - name: DB_SERVICE
      value: "geoboundaries-postgres-service"
    - name: DB_NAME
      value: "geoboundaries"
    - name: DB_USER
      value: "geoboundaries"
    - name: DB_PASSWORD
      value: ""
    volumeMounts:
    - mountPath: /sciclone
      name: nfs-mount
  volumes:
  - name: nfs-mount
    nfs:
      server: "128.239.59.144"
      path: "/sciclone"
---
apiVersion: v1
kind: Service
metadata:
  name: geoboundaries-monitor-service
  namespace: geoboundaries
spec:
  type: ClusterIP
  selector:
    app: geoboundaries-monitor
  ports:
  - port: 80
    targetPort: 5000
