apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoboundaries-monitor
  namespace: geoboundaries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoboundaries-monitor
  template:
    metadata:
      labels:
        app: geoboundaries-monitor
    spec:
      securityContext:
        runAsUser: 71032
        runAsGroup: 9915
      containers:
      - name: monitor
        image: ghcr.io/wmgeolab/gb-monitor:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_SERVICE
          value: "geoboundaries-postgres-service"
        - name: DB_NAME
          value: "geoboundaries"
        - name: DB_USER
          value: "geoboundaries"
        - name: DB_PASSWORD
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: geoboundaries-monitor-service
  namespace: geoboundaries
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30081  # Monitor dashboard port
  selector:
    app: geoboundaries-monitor
