apiVersion: v1
kind: Pod
metadata:
  name: geoboundaries-postgres
  namespace: geoboundaries
  labels:
    app: geoboundaries-postgres
spec:
  securityContext:
    runAsUser: 71032  # Required for NFS compatibility
    runAsGroup: 9915  # Required for NFS group access
    fsGroup: 9915     # Ensures group ownership for the data directory
  containers:
  - name: postgres
    image: postgis/postgis:14-3.3  # PostGIS-enabled PostgreSQL image
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: "geoboundaries"  # User to be created on first run
    - name: POSTGRES_PASSWORD
      value: ""  # Empty password (trust authentication enabled)
    - name: POSTGRES_DB
      value: "geoboundaries"  # Database to be created on first run
    - name: POSTGRES_HOST_AUTH_METHOD
      value: "trust"  # Allow connections without a password
    args:
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "idle_in_transaction_session_timeout=60000"
      - "-c"
      - "statement_timeout=30000"
      - "-c"
      - "log_min_duration_statement=1000"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "shared_buffers=8GB"
      - "-c"
      - "effective_cache_size=24GB"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "max_wal_size=2GB"
      - "-c"
      - "min_wal_size=256MB"
      - "-c"
      - "checkpoint_timeout=10min"
      - "-c"
      - "max_worker_processes=16"
      - "-c"
      - "max_parallel_workers=8"
      - "-c"
      - "max_parallel_workers_per_gather=4"
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data  # Persistent data directory
    resources:
      requests:
        memory: "32Gi"
        cpu: "16"
      limits:
        memory: "64Gi"
        cpu: "32"
  volumes:
  - name: postgres-data
    nfs:
      server: 128.239.59.144  # Replace with your NFS server IP
      path: /sciclone/geograd/geoBoundaries/postgres  # NFS path for PostgreSQL data storage
---
apiVersion: v1
kind: Service
metadata:
  name: geoboundaries-postgres-service
  namespace: geoboundaries
spec:
  selector:
    app: geoboundaries-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
