apiVersion: v1
kind: Pod
metadata:
  name: check-and-populate-tasks
  namespace: geoboundaries
  labels:
    app: check-and-populate-tasks
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 71032    # User ID for accessing NFS
    runAsGroup: 9915    # Group ID for accessing NFS
  containers:
    - name: check-and-populate-tasks
      image: ghcr.io/wmgeolab/gb-base:latest
      command: ["/bin/bash", "-c"]
      args:
        - |
          export KUBECONFIG=/sciclone/geograd/geoBoundaries/.kube/config && \
          python /scripts/modules/queue_operator.py
      env:
        - name: DB_SERVICE
          value: "geoboundaries-postgres-service"
        - name: DB_NAME
          value: "geoboundaries"
        - name: DB_USER
          value: "geoboundaries"
        - name: DB_PASSWORD
          value: ""
      volumeMounts:
        - name: script-volume
          mountPath: /scripts
        - name: kubeconfig-volume
          mountPath: /sciclone  # Mount NFS base directory
  volumes:
    - name: script-volume
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd/geoBoundaries/geoBoundaryBot/geoBoundaryBuilder
    - name: kubeconfig-volume
      nfs:
        server: 128.239.59.144
        path: /sciclone
