apiVersion: v1
kind: Pod
metadata:
  name: adminer
  namespace: geoboundaries
  labels:
    app: adminer
spec:
  containers:
    - name: adminer
      image: adminer:latest  # Lightweight Adminer container image
      ports:
        - containerPort: 8080
      env:
        - name: ADMINER_DESIGN  # Optional: Theme for the UI
          value: "pepa-linha"    # A clean Adminer design

---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  namespace: geoboundaries
  labels:
    app: adminer
spec:
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080         # Port to expose Adminer UI
      targetPort: 8080   # Adminer listens on 8080
  type: NodePort         # Use NodePort to expose the service externally
