apiVersion: v1
kind: Pod
metadata:
  name: worker-operator
  namespace: geoboundaries
  labels:
    app: worker-operator
spec:
  restartPolicy: Never  # Restart policy at the Pod level
  securityContext:
    runAsUser: 71032    # User ID for accessing NFS
    runAsGroup: 9915    # Group ID for accessing NFS
  containers:
    - name: worker-operator
      image: ghcr.io/wmgeolab/gb-base:latest
      command: ["/bin/bash", "-c"]
      args:
        - |
          export KUBECONFIG=/sciclone/geograd/geoBoundaries/.kube && \
          cd /sciclone/geograd/geoBoundaries/geoBoundaryBot/geoBoundaryBuilder/modules/
          python worker_operator.py
      env:
        - name: DB_SERVICE
          value: "geoboundaries-postgres-service"
        - name: DB_NAME
          value: "geoboundaries"
        - name: DB_USER
          value: "geoboundaries"
        - name: DB_PASSWORD
          value: ""
      volumeMounts:
        - name: sciclone-volume
          mountPath: /sciclone  # Mount kubeconfig directory
  volumes:
    - name: sciclone-volume
      nfs:
        server: 128.239.59.144
        path: /sciclone
